### ISSUE TITLE
share command

### ISSUE THREAD

**Issue by courtneyum** [gharveymn/matshare#2]
Parameters: the name of the data to be shared and the data itself.
Return value: none

1. By calling shm_open, create a shared memory object with the same name as the name passed in as a parameter proceeded by a slash (/). **The O_CREAT flag may be needed to prevent problems in the case that an object was earlier opened under the same name and then unlinked**
2. Call fstat() to check that the size of this object is 0 (hasn't already been created). If it has already been created we can either:
    a) assume that that they are the same data and return early.
    b) unlink the already present object and return to step 1.  (This option would assume that the data 
    passed into this call is newer than the data stored in the already present object and that the data in 
    the already present object is garbage).
3. Call ftruncate() to set the size of this object (it is zero upon creation).  
4. Use the file descriptor obtained by the call to shm_open to mmap the shared memory location. 
5. Use mx functions to determine the type and size of the data.  Place this information into a uniformly 
    formatted header to come before the actual data in the shared memory.
6. Duplicate the data into the pointer returned by mmap. 

Cleanup:
1. unmap the object.
2. close the file descriptor.

**For later: Make sure the name of the created object gets added to the queue of all open objects.

**Comment by gharveymn** [comment]
We have to be careful here because we are essentially doing a manual `malloc` by creating the file in primary memory, however the MATLAB function `mxMalloc` is special in that it implements a 32-byte alignment required by AVX vectors when allocating memory (probably, no actual documentation). I'm not totally sure how to do alignment properly so your help would be great on that.

Do you figure we should return the newly shared variable when sharing, or require the user to use the `get` function? I ask because we should expect to be freeing the variable when it gets shared, so if we don't return it then there is a time where the variable is completely hidden to the user. However, it's inelegant to have two functions returning the same thing.
